update nopwsudo

diff --git a/script/nopwsudo b/script/nopwsudo
--- a/script/nopwsudo
+++ b/script/nopwsudo
@@ -1,6 +1,10 @@
+#/bin/env bash
 
+if ! command -v tee &>/dev/null; then
+  echo "tee binary not found in path, exiting..."
+  exit 1
+fi
 
-# grant all admin users of ubuntu linux nopassws sudo access via /etc/sudoers.d/admin config file
 if [[ "$(uname)" == "Linux" ]]; then
   if ! [[ -f /etc/sudoers.d/admin ]]; then
     echo "Granting all admin users nopasswd sudo access..."
@@ -9,8 +13,8 @@ if [[ "$(uname)" == "Linux" ]]; then
 fi
 
 if [[ "$(uname)" == "Linux" ]]; then
-  if ! [[ -f /etc/sudoers.d/admin ]]; then
+  if ! [[ -f /etc/sudoers.d/adm ]]; then
     echo "Granting all admin users nopasswd sudo access..."
-    echo "%admin ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/admin
+    echo "%adm ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/adm
   fi
 fi
